# Generated by Django 4.1.2 on 2022-11-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
