# Generated by Django 4.1.2 on 2022-11-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dormitory',
            field=models.CharField(default='гуртожиток', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='exact_place',
            field=models.CharField(default="З'ясується на місці", max_length=100),
        ),
    ]
