# Generated by Django 4.1.2 on 2022-11-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_help', '0002_report_dormitory_report_exact_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
