# Generated by Django 4.1.2 on 2022-11-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_help', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(default=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='report',
            name='dormitory',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='exact_place',
            field=models.CharField(max_length=100),
        ),
    ]
