# Generated by Django 4.1.2 on 2022-11-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_help', '0004_report_email_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dormitory',
            field=models.IntegerField(choices=[(1, 'First'), (4, 'Fourth')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='problem_type',
            field=models.CharField(choices=[('Електрик', 'Electricity'), ('Столяр', 'Carpenter'), ('Сантехнік', 'Plumber'), ('Не визначено', 'Undefined')], max_length=70),
        ),
    ]
