# Generated by Django 4.1.2 on 2022-11-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_help', '0005_alter_report_dormitory_alter_report_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='date_report',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='report_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostel_help.report'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='dormitory',
            field=models.IntegerField(choices=[(1, '1 гуртожиток'), (4, '4 гуртожиток')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='problem_type',
            field=models.CharField(choices=[('Електрик', 'Електрик'), ('Столяр', 'Столяр'), ('Сантехнік', 'Сантехнік'), ('Не визначено', 'Не визначено')], default='Не визначено', max_length=70),
        ),
    ]
