# Generated by Django 4.1.2 on 2022-11-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_help', '0006_contact_date_contact_date_report_contact_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_emails', to='hostel_help.report'),
        ),
    ]
