# Generated by Django 4.1.2 on 2022-12-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_help', '0007_alter_contact_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='Неактивна', max_length=50),
        ),
    ]
